### ISSUE TITLE
missing "Testing Decision Operation" in run configurations

### ISSUE THREAD

**Issue by dhpalan** [DecisionsDev/ruledesigner#11]
As a follow up of the issue #10 (missing "DVS Decision Operation" in run configurations)
We noticed that the launch configuration called `Testing Decision Operation`? is also missing in the Rule Designer when installed from marketplace.

We were trying to follow the instructions from here to validate rulesets against scenarios:
https://www.ibm.com/support/knowledgecenter/SSQP76_8.10.x/com.ibm.odm.dserver.rules.designer.test/topics/tsk_simple_test_ruleset_rd.html

---

Left: Rule designer as plugin on existing eclipse.
Right: on-prem installation package downloaded from IBM Passport Advantage

![image](https://user-images.githubusercontent.com/46791526/83238984-7bf4dd00-a197-11ea-8fda-ce630149aacc.png)

**Comment by lunyi476** [comment]
Same issue as "missing "Testing Decision Operation" in run configurations #11":

I had the same issue when I installed Eclipse Oxygen 4.7.3 + ODM 8.10.5.1.
First I created test Excel scenario file, when try to set debug configuration, the pop-up screen had no "Testing Decision Operation" selection (only Decision Operation). So, I cannot use Excel Sheet to run debug or test.

Please help.

**Comment by lunyi476** [comment]
![Rule_Designer_Debug_Config_Issue](https://user-images.githubusercontent.com/6955932/122812062-3376f880-d29f-11eb-83a8-8a629cf2af73.png)

**Comment by Grey2k** [comment]
Same issue

**Comment by alainrobert** [comment]
Testing and simulation are not available in the Rule Designer for developers, they are only accessible from the on premise installation as they require that the rule execution server is installed locally. 

You can suggest an improvement here https://ideas.ibm.com/new-idea use the product **IBM Cloud Pak for Business Automation (Program 30A8K): Automation Decision Services (ADS)**

**Comment by alainrobert** [comment]
Unfortunately no change in this area. This is important to you so please consider opening a request for enhancement so the team can assess the work for a future release.

**Comment by lgrateau** [comment]
closing no new about RFE
