### ISSUE TITLE
Run Configurations -> Decision Operation Nullpointer Exception - ODM 8.11

### ISSUE THREAD

**Issue by amitshah56** [DecisionsDev/ruledesigner#14]
While creating an instance of new decision operation from run configurations with ODM 8.11 for Eclipse IDE version eclipse-jee-2020-06-R-win32-x86_64, it throws the attached error.
[DecisionOperation_ConfigurationError.log](https://github.com/ODMDev/ruledesigner/files/8054278/DecisionOperation_ConfigurationError.log)

Kindly seek your assistance for resolution

**Comment by lgrateau** [comment]
too old
