### ISSUE TITLE
Deployment Configuration -> Target server cannot be reached

### ISSUE THREAD

**Issue by amitshah56** [DecisionsDev/ruledesigner#15]
Hello, 

The test connection for the configured target RES server fails under deployment configuration with the attached error. 

ODM version is 8.11 and the Eclipse IDE version is eclipse-jee-2020-06-R-win32-x86_6
[TestConnection_Error.log](https://github.com/ODMDev/ruledesigner/files/8054279/TestConnection_Error.log)

Regards,
Amit

**Comment by lgrateau** [comment]
too old
