### ISSUE TITLE
Unable to install Rule Designer

### ISSUE THREAD

**Issue by Ruchirshah1211** [DecisionsDev/ruledesigner#16]
I am getting below error while trying to install rule designer in eclipse environment.
--------Error------------
Cannot complete the install because one or more required items could not be found.
  Software being installed: IBM ODM for Developers - Rule Designer 8.11.0.0-IF004 (com.ibm.rules.studio.container.feature.feature.group 8.11.0.0-IF004)
  Missing requirement: Rule Designer Shared 8.11.0.0-IF004 (ilog.rules.studio.shared 8.11.0.0-IF004) requires 'osgi.bundle; javax.servlet 3.1.0' but it could not be found
  Cannot satisfy dependency:
    From: IBM ODM for Developers - Rule Designer 8.11.0.0-IF004 (com.ibm.rules.studio.container.branding 8.11.0.0-IF004)
    To: osgi.bundle; ilog.rules.studio.shared [8.11.0,8.11.1)
  Cannot satisfy dependency:
    From: IBM ODM for Developers - Rule Designer 8.11.0.0-IF004 (com.ibm.rules.studio.container.feature.feature.group 8.11.0.0-IF004)
    To: org.eclipse.equinox.p2.iu; com.ibm.rules.studio.container.branding [8.11.0.0-IF004,8.11.0.0-IF004]
    
  If anyone know solution please guide me.

**Comment by alfred4ibm** [comment]
same here!!

**Comment by jrmfong** [comment]
same here x 2!!
------Error Log------
Cannot complete the install because one or more required items could not be found.
  Software being installed: IBM ODM for Developers - Rule Designer 8.11.0.1-IF001 (com.ibm.rules.studio.container.feature.feature.group 8.11.0.1-IF001)
  Missing requirement: IBM Decision Server Designer Base 8.11.0.1-IF001 (com.ibm.rules.studio.base.feature.feature.group 8.11.0.1-IF001) requires 'org.eclipse.equinox.p2.iu; org.eclipse.emf.feature.group [2.21.0,3.0.0)' but it could not be found
  Cannot satisfy dependency:
    From: IBM ODM for Developers - Rule Designer 8.11.0.1-IF001 (com.ibm.rules.studio.container.feature.feature.group 8.11.0.1-IF001)
    To: org.eclipse.equinox.p2.iu; com.ibm.rules.studio.base.feature.feature.group 0.0.0

**Comment by Frank3354** [comment]
For anyone that runs into this issue: Make sure you install Eclipse Java Enterprise Edition 2020-06 as per IBM documentation: https://www.ibm.com/docs/en/odm/8.11.0?topic=8110-installing-rule-designer

I tried installing Rule Designer in a newer version of Eclipse and I was getting the same error messages mentioned in the previous comments. 

Feel free to mark this issue as resolved.

**Comment by alfred4ibm** [comment]
No Eclipse 2020-06 for macbook M1 / aarch64 though. Tried to install x64, but not able to install.

**Comment by MTamPham** [comment]
Getting the same error although installed Eclipse 2020-06 as per IBM documentation. I am using Mac M1 and having multiple JDK versions installed. Wondering if Java 17 could cause the failing in plugin installation?

Message:
Server returned lastModified <= 0 for https://raw.githubusercontent.com/ODMDev/ruledesigner/8.11.0/p2/artifacts.xml

Exception Stack Trace:
An exception stack trace is not available.

Session Data:
eclipse.buildId=4.16.0.I20200604-0540
java.version=17.0.4.1
java.vendor=Azul Systems, Inc.
BootLoader constants: OS=macosx, ARCH=x86_64, WS=cocoa, NL=en_US_EN
Framework arguments:  -product org.eclipse.epp.package.jee.product -product org.eclipse.epp.package.jee.product -product org.eclipse.epp.package.jee.product -keyring /Users/XXXXXXXX/.eclipse_keyring
Command-line arguments:  -os macosx -ws cocoa -arch x86_64 -product org.eclipse.epp.package.jee.product -product org.eclipse.epp.package.jee.product -data file:/Users/XXXXXXXX/eclipse-workspace/ -product org.eclipse.epp.package.jee.product -keyring /Users/XXXXXXXX/.eclipse_keyring

**Comment by alainrobert** [comment]
Rule Designer only works with JDK 8 we recommend this one for M1
https://github.com/ibmruntimes/semeru8-binaries/releases/download/jdk8u372-b07_openj9-0.38.0/ibm-semeru-open-8-jdk-1.8.0.372.b07_0.38.0-1.aarch64.rpm

This issue looks like a connection issue, check that you can access the URL in the error message.

Note that we also recommend install from this update site to benefit from the update as they become available:
https://raw.githubusercontent.com/DecisionsDev/ruledesigner/8.11.0.x-ifix/p2

**Comment by lgrateau** [comment]
no feedback until 2023. Closing it
