### ISSUE TITLE
An internal error occurred during: "RuleApp Deployment". Cannot invoke "java.lang.reflect.Method.invoke(Object, Object[])" because "com.sun.xml.bind.v2.runtime.reflect.opt.Injector.defineClass" is null

### ISSUE THREAD

**Issue by gosocial2** [DecisionsDev/ruledesigner#19]
This error occurs when trying to deploy a rule app from Eclipse 2024‑03 M2 modeling to IBM on Docker 8.12.x

An internal error occurred during: "RuleApp Deployment". Cannot invoke "java.lang.reflect.Method.invoke(Object, Object[])" because "com.sun.xml.bind.v2.runtime.reflect.opt.Injector.defineClass" is null

which already works and is deployable on ODM 8.10.5 (commercial) on Windows

**Comment by lgrateau** [comment]
@gosocial2 ODM 8.12 should be installed with this requirements:
For 8.12.0.1 Release:

-     Eclipse IDE 2022-06 R (4.24) Modeling Tools Packages
-     JDK 11
-     You can find all available releases at this location : https://github.com/DecisionsDev/ruledesigner/releases
