### ISSUE TITLE
Unable to install ODM 8.11 on eclipse 2020-06 R

### ISSUE THREAD

**Issue by tghate** [DecisionsDev/ruledesigner#20]
Getting below error trying to install ODM 8.11.1

Unable to read repository at https://raw.githubusercontent.com/DecisionsDev/ruledesigner/8.11.1/p2/content.xml.
Unable to read repository at https://raw.githubusercontent.com/DecisionsDev/ruledesigner/8.11.1/p2/content.xml.
PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target

Please help with resolution

**Comment by alainrobert** [comment]
The actual file you would want to search is 
https://raw.githubusercontent.com/DecisionsDev/ruledesigner/8.11.1/p2/compositeContent.xml

In Eclipse however for the site you don't specify the filename 

Here you seem to have an issue with the github.com certificate. Download the certificate with your browser and add it to the cacerts in the JVM running eclipse.
https://www.ibm.com/docs/en/odm/8.12.0?topic=designer-importing-security-certificate-in-rule

**Comment by lgrateau** [comment]
Closing it. No feedbacks from the user
